### ISSUE TITLE
change command: option in docker-compose.yml

### ISSUE THREAD

**Issue by arr0n** [StamusNetworks/Amsterdam#12]
i was wondering if it would make sense for you to change the command option in the docker-compose file.  How it is currently configured means expanding logstash to take other inputs is difficult.  A small change from:
'command:  -f /etc/logstash/logstash.conf'
to
'command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/'
and of course changing the setup script to place the logstash.conf in the conf.d folder.  

However it would mean the the logstash would be able to be configured inline with the documentation for it.  

Just a suggestion.  Great work guys

Arr0n

**Comment by regit** [comment]
It really make sense. Feel free to propose a pull request with that. You just need to update the src/template/docker-compose template.

**Comment by arr0n** [comment]
Will do, i'm about to finish up for the day but i shall get on it tomorrow

**Comment by arr0n** [comment]
So i edited the src/template/docker-compose.yml2 file as suggested, and in the src/config/logstash added a conf.d and put the logstash.conf file in there however whenever i use the setup command (i.e. amsterdam -d test -i wlan0 setup) it seems to deploy with the old config and old location.  I'm not sure what i'm missing or forgotten to do

**Comment by regit** [comment]
@arr0n you need to install it with 'python setup.py install' as the copy is made from installation directory

**Comment by arr0n** [comment]
@regit that worked thank you, i'll do a pull request now

**Comment by arr0n** [comment]
@regit i've done a pull request (i think) hopefully it'll make sense

**Comment by regit** [comment]
PR applied, thanks!
