### ISSUE TITLE
Elasticsearch staying yellow 

### ISSUE THREAD

**Issue by arr0n** [StamusNetworks/Amsterdam#14]
I've noticed that elasticsearch stays in a yellow status and doesn't change to green.  Apparently this is a common issue with the default deployment of it, and its due to how the default configuration handles nodes.  I managed to fix this by following this  

"This is a common issue arising from the default index setting, in particularly, when you try to replicate on a single node. To fix this with transient cluster setting, do this:

curl -XPUT http://localhost:9200/_settings -d '{ "number_of_replicas" :0 }'

Next, enable the cluster to reallocate shards (you can always turn this on after all is said and done):

curl -XPUT http://localhost:9200/_cluster/settings -d '
{
    "transient" : {
        "cluster.routing.allocation.enable": true
    }
}'

Now sit back and watch the cluster clean up the unassigned replica shards. If you want this to take effect with future indices, don't forget to modify elasticsearch.yml file with the following setting and bounce the cluster:

index.number_of_replicas: 0
"

from here http://stackoverflow.com/questions/23656458/elasticsearch-what-to-do-with-unassigned-shards

of course i used docker exec -it to do it

**Comment by pevma** [comment]
This is how we do it with SELKS btw - 
https://github.com/StamusNetworks/SELKS/blob/master/staging/config/hooks/chroot-inside-Debian-Live.chroot#L189

so i think it is safe to add that here as well.

**Comment by regit** [comment]
Fixed in Amsterdam 0.8.

Note: you need an instance with no data at start to get it green
