### ISSUE TITLE
High I/O usage

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/Amsterdam#17]
When running Amsterdam I am taking a huge hit on my datastore on:

[Picture](http://i.imgur.com/IKMsBPv.png)

I am not swapping to the disk:

> ```
>           total        used        free      shared  buff/cache   available
> ```
> 
> Mem:           4799        2768         461          16        1569        1745
> Swap:          2063           0        2063

How can I trace the high I/O usage back to a specific part of Amsterdam?

**Comment by regit** [comment]
I would bet on Elasticsearch. You should be able to see which process is using I/O from the host. Then given the process command line you will see which one is responsible.

**Comment by Eagleman7** [comment]
Is it normal that Elasticsearch produces so much latency?

**Comment by Eagleman7** [comment]
Can be closed
