### ISSUE TITLE
https access not working

### ISSUE THREAD

**Issue by inliniac** [StamusNetworks/Amsterdam#26]
After doing a fresh install on Ubuntu 16.04, everything appears to be working except the https access. I can open the individual apps by going to http://localhost:8000 and the other ports.

**Comment by pevma** [comment]
I just tried on Debian Jessie , the links as instructed here - 
https://github.com/StamusNetworks/Amsterdam#usage  
worked as expected in my case.

**Comment by Eagleman7** [comment]
If you installed with pip you are using an older version which is still working on port 8000. If you install with git this should work on port 80.

**Comment by inliniac** [comment]
Yeah I installed from pip on ubuntu, using the instructions on the github page. If the problem is that this installs an old version, then either the pip version needs to be updated or the doc needs to be updated.

**Comment by Eagleman7** [comment]
@regit is it still on your todo list?

**Comment by regit** [comment]
0.7 created and pushed.
