### ISSUE TITLE
Kibana Init issue?

### ISSUE THREAD

**Issue by mgaulton** [StamusNetworks/Amsterdam#3]
I just installed  and am getting the below when I connect to Kibana. I also noticed a few "this will be depreacated messages". Wondering what I need to do to update/resolve this?

Configure an index pattern
In order to use Kibana you must configure at least one index pattern. Index patterns are used to identify the Elasticsearch index to run search and analytics against. They are also used to configure fields.
 Index contains time-based events  
 Use event times to create index names [DEPRECATED]
Index name or pattern
Patterns allow you to define dynamic index names using \* as a wildcard. Example: logstash-*
logstash-*

logstash_1      | Error: The setting `host` in plugin `elasticsearch` is obsolete and is no longer available. Please use the 'hosts' setting instead. You can specify multiple entries separated by comma in 'host:port' format. If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask.
logstash_1      | You may be interested in the '--configtest' flag which you can
logstash_1      | use to validate logstash's configuration before you choose
logstash_1      | to restart a running system.
amsterdam_logstash_1 exited with code 1

scirius_1       | /usr/local/lib/python2.7/dist-packages/django_tables2/tables.py:175: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
scirius_1       |   attrs["base_columns"] = SortedDict(parent_columns)
scirius_1       |
scirius_1       | /usr/local/lib/python2.7/dist-packages/django_tables2/tables.py:197: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.

scirius_1       |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
scirius_1       |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

**Comment by regit** [comment]
Hello

For logstash you can edit $AMSTERDAM_DIR/config/logstash/logstash.conf and restart amsterdam to see if issue is fixed. When done, it would be great if you could do a PR by reporting your changes to src/config/logstash/logstash.conf.

For kibana I don't understand when do you see this message. There is no setup done in amsterdam so any message should be a stock message.

**Comment by mgaulton** [comment]
I'll take a look at the logstash.

Soon as I load the kibana page, i get it.
http://localhost:5601/app/kibana#/settings/indices/?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))

**Comment by regit** [comment]
Which Amsterdam version do you use ?

**Comment by mgaulton** [comment]
fresh install from the repo

**Comment by regit** [comment]
@mgaulton: I'm closing it as I'm not seeing anybody that reproduce that. Feel free to reopen it if needed.
