### ISSUE TITLE
HTTP 404 when updating ruleset

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/Amsterdam#31]
Sometimes when updating the rules I am getting:
502 Bad Gateway

nginx/1.11.0

This happens on this page:

https://ips.corp.domain.com/suricata/update

**Comment by regit** [comment]
Looks more like a 502 ;)

Do you have an idea of how long it takes to update the ruleset ?

**Comment by infiniteproject** [comment]
#37

**Comment by kedf** [comment]
Hi,
Same issue here but for me it's every time and increasing timeout don't resolve it.
I'm getting 502 error always after 30s.

error log from ams_nginx_1 (/var/log/nginx/stamus.error.log)
 `2016/07/07 14:35:47 [error] 6#6: *28 upstream prematurely closed connection while reading response header from upstream, client: 10.47.0.2, server: amsterdam, request: "POST /suricata/update HTTP/1.1", upstream: "http://172.17.0.6:8000/suricata/update", host: "attic", referrer: "https://attic/suricata/update"
`

**Comment by Eagleman7** [comment]
timeout has been increased, no more 502 when updating
