### ISSUE TITLE
Error in src/amsterdam.py

### ISSUE THREAD

**Issue by ghost** [StamusNetworks/Amsterdam#41]
Hello,

There is an error in this file src/amsterdam.py in this line "from docker import Client". It's a small 'c' letter not a capital one.

**Comment by regit** [comment]
What version of dockerpy do you have ?

**Comment by ghost** [comment]
I'm using 1.8.0 version

**Comment by ghost** [comment]
Your code should be changed anyway cause the recent version of docker-py has changed the name of docker.client to docker.APIClient
https://github.com/docker/docker-py/releases

**Comment by regit** [comment]
Could you post the traceback of the error? I'm having issue reproducing the problem and I don't find reference to with lower case client in the 1.8.0 doc.

**Comment by ghost** [comment]
If you use ubuntu 16.10 or the latest docker image of ubuntu, they both use 1.8.0. And if you try to import docker.Client, you'll see that it does not exist, only the lower case exist.

**Comment by regit** [comment]
I pushed to master a patch that could correct things but I don't manage to reproduce the issue.

**Comment by regit** [comment]
No news. Closing the bug. Please reopen if needed.
