### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by redhandpl** [StamusNetworks/Amsterdam#42]
Hi,

I've installed the latest version of Amsterdam and have containers running. When accessing localhost I can see everything. The problem is when accessing remotely by IP address. I get "Internal Server Error".

Do I have to configure additionally something?

**Comment by regit** [comment]
Yes but it should be documented. You need to add ALLOWED_HOSTS in `config/scirius/local_settings.py` See https://docs.djangoproject.com/en/1.10/ref/settings/#allowed-hosts for complete information.

To authorize from anywhere, add that to the end of local_settings.py and restart amsterdam:
```
ALLOWED_HOSTS = [ '*' ]
```

**Comment by redhandpl** [comment]
Ah, the django variable. Thanks. It works.
