### ISSUE TITLE
Managing logs

### ISSUE THREAD

**Issue by redhandpl** [StamusNetworks/Amsterdam#46]
Hi,

In SELKS there is a https://github.com/StamusNetworks/SELKS/wiki/Logrotate. How do you manage logs here?
Is it good idea to manage them through the main host and SIGHUP with 'docker exec'?

**Comment by regit** [comment]
It is currently not done in Amsterdam. Logs are present in the data directory under suricata/ for the JSON so it should be possible to logrotate them from the host and send a signal to suricata to warn it about logrotation.

**Comment by redhandpl** [comment]
Are planning to manage logs in Amsterdam?
For now I will try to rotate the from the host.
