### ISSUE TITLE
not working, alas

### ISSUE THREAD

**Issue by mslayton-abra** [StamusNetworks/Amsterdam#49]
Really love the idea of Amsterdam, but the install has been a problem. 
I'm probably just missing a large collection of things obvious to people 
who are closer to the project. 

Install took quite awhile to get through.  Many missing and sometimes 
circular dependencies.   I think I have it installed properly now (at least
the setup.py runs to completion without errors).

However, when I run the configure command:  
> amsterdam -d ams -i <my_device_port> setup 
I get a backtrace that ends with: 

> requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

Tried several different versions of the above command with different ./data directories.  
Same error.   Also looked through other issues filed -- nothing seemed to 
match this, but again, I do not have much context yet. 

My install:  CentOS7;  Python 2.7.

**Comment by regit** [comment]
Is docker started ? Do you get something if you run `docker ps` ?

**Comment by mslayton-abra** [comment]
Yes, this was my problem.  Docker needs to be running, obviously.   Thanks --

**Comment by mslayton-abra** [comment]
I seem to have running processes now, and I can get a response from <my_ip>:9200. 
(ElasticSearch produces a json response). 

However, all other ports refuse to respond, e.g. when I go to:   https://<my_ip>/
I get a 'connection refused'. 

I noticed that none of the components appear to be able to speak to each other. 
For example, the proxy_forward directive in nginx config points to:  http://scirius:8000/

Yet, the local host cannot resolve the name 'scirius', hence, failure.  

 Am I missing another obvious thing?   
I've updated with the latest changes including ALLOWED_HOSTS = ['*'] in the scirius config.

**Comment by mslayton-abra** [comment]
It seems that the nginx container run by amsterdam never binds to any ports, at least in my case, which runs on centos7 and has no customizations. 

nginx is running within the container, but isn't listening on any ports, and doesn't produce any log messages.  I'm guessing there is some config issue with the container.  

I'll post again when I've gotten to the bottom of it.   Others may be seeing the same issue.
