### ISSUE TITLE
Error on the command pip install amesterdam

### ISSUE THREAD

**Issue by phoenixml** [StamusNetworks/Amsterdam#57]
Hi Stamus dev's and community,

While setup amesterdam I am getting module error on line 26
from OpenSSL import crypto
ImportError: No module named OpenSSL

Any Ideas to solve the issue will be appreciated.

**Comment by mostafa** [comment]
requirements:
```
argparse==1.4.0
docker-compose==1.9.0
pyOpenSSL==18.0.0
```

**Comment by biote3h** [comment]
a requirement.txt would helps.
