### ISSUE TITLE
Suricata can't start due to missing file

### ISSUE THREAD

**Issue by bladeswords** [StamusNetworks/Amsterdam#7]
Suricata fails to start and supervisor states too many failed attempts to start suricata.

The following were the steps I took to fix the issue (missing file).  If I have time I will make a pull request.

/usr/bin/suricata -T /etc/suricata/suricata.yaml
26/12/2015 -- 21:26:03 - <Info> - Running suricata under test mode
26/12/2015 -- 21:26:03 - <Notice> - This is Suricata version 3.0RC3 RELEASE
26/12/2015 -- 21:26:13 - <Warning> - [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "/etc/suricata//threshold.config": No such file or directory
26/12/2015 -- 21:26:13 - <Notice> - Configuration provided was successfully loaded. Exiting.

touch /etc/suricata/threshold.config

/usr/bin/suricata -T /etc/suricata/suricata.yaml
26/12/2015 -- 21:26:46 - <Info> - Running suricata under test mode
26/12/2015 -- 21:26:46 - <Notice> - This is Suricata version 3.0RC3 RELEASE
26/12/2015 -- 21:26:56 - <Notice> - Configuration provided was successfully loaded. Exiting.

**Comment by regit** [comment]
Thanks for the report @bladeswords but missing threshold.config is not a fatal error for suricata. So if suricata is not starting in your case there may be another issue.

**Comment by regit** [comment]
No update, closing.
