### ISSUE TITLE
Scirius not starting due to missing +x

### ISSUE THREAD

**Issue by ravens** [StamusNetworks/Amsterdam#9]
Hi,

On a fresh ubuntu 14.04, I had to add a statement in the Dockerfile:
"RUN chmod ugo+x /opt/selks/bin/scirius.sh" to force execution right on scirius entrypoint script - otherwise container will not start with error "System error: exec: "/opt/selks/bin/scirius.sh": permission denied".

[diff.txt](https://github.com/StamusNetworks/Amsterdam/files/72478/diff.txt)

**Comment by regit** [comment]
Merci @ravens :) Patch applied but I've made a stupid typo on you nickname. Sorry for that.
